messages:
  openMine: '&aШахта &6"%mine_name%"&a открыта!'
  closeMine: '&aШахта &6"%mine_name%"&a закрыта!'
  regenerateMine: '&aШахта &6"%mine_name%"&a успешно обновилась!'
  mineRegenerateIn: 'Шахта &6"%mine_name%"&r обновится через %seconds% секунд'
  mineWithIdNotExist: '&cШахты с id &6%mine_id%&c не существует'
  mineWithIdAlreadyExist: '&cШахты с id &6%mine_id%&c уже существует'
  notEnoughRights: '&cНедостаточно прав'
  commandUseOnlyForPlayers: 'Использовать команду может только игрок'
  notEnoughArgs: '&cНе были переданы все аргументы'
  mineSuccessRename: '&aШахта успешно переименована'
  mineSuccessDelete: '&aШахта удалена успешно'
  mineSuccessSetInterval: '&aИнтервал шахты успешно установлен'
  mineSuccessSetSpawn: '&aТочка спавна установлена успешно'
  mineSuccessGenerate: '&aШахта сгенерирована успешно'